project:
  title: "QSlides"
  type: website
  output-dir: docs

format:
  revealjs:
    preview-links: auto
    multiplex: true
    slide-number: true
    logo: ../qlvl.png
    theme: default
    css: ../styles.css
  html:
    theme: united
    css: styles.css
    toc: true
    code-link: true
execute:
  echo: false
  freeze: auto
