---
title: "Slides by Chiara Paolini"
format: html
number-sections: true
---

These are slides presented at various conferences by Chiara Paolini. If you would like to download slides as PDF, please follow the [instructions in the Quarto documentation](https://quarto.org/docs/presentations/revealjs/presenting.html#print-to-pdf).

# [Linguists' Day 2022 (CBL-BKL)](BKL_22/index.qmd){target="_blank"}

These are the slides presented at the Belgian Society of Linguistics on 21-10-2022 with Benedikt Szmrecsanyi and Mariana Montes. [Read the abstract](BKL_22/abstract.qmd)

<div>

```{=html}
<iframe class="slide-deck" src="BKL_22/index.html"></iframe>
```

</div>

# [QLVL Colloquium](QLVL_colloquium/index.qmd){target="_blank"}

These are the slides presented at the QLVL Colloquium on 4-11-2022. [Read the abstract](QLVL_colloquium/abstract.qmd)

<div>

```{=html}
<iframe class="slide-deck" src="QLVL_colloquium/index.html"></iframe>
```

</div>


# [Taal en Tongval](Taal_tongval/index.qmd){target="_blank"}

These are the slides to be presented at the Taal en Tongval Colloquium on 18-11-2022 with Benedikt Szmrecsanyi and Mariana Montes. [Read the abstract](Taal_tongval/abstract.qmd)

<div>

```{=html}
<iframe class="slide-deck" src="Taal_tongval/index.html"></iframe>
```

</div>

<!-- # [Conference](Conf_dir/index.qmd){target="_blank"} -->

<!-- These are the slides presented at ... -->

<!-- [Read the abstract](Conf_dir/abstract.qmd) -->

<!-- <div> -->

<!-- ```{=html} -->

<!-- <iframe class="slide-deck" src="Conf_dir/index.html"></iframe> -->

<!-- ``` -->

<!-- </div> -->
