---
title: "Annotation goes distributional:"
subtitle: "Modeling semantic predictors of the dative alternation using vector space models"
author:
  - Chiara Paolini
format: html
---

Chiara Paolini is a 2nd year PhD student, under the supervision of Benedikt Szmrecsanyi. In her talk, she will present a distributional semantics approach to investigate how much the semantic characteristics of the lexical material in the costituents predict the choice between the two variants of the English dative alternation. 
To accomplish this goal, automatically-generated, corpus based semantic predictors are obtained in a bottom-up fashion from type-level distributional models. These are then fitted in statistical models together with manually-annotated internal-language predictors to understand and determine their explanatory power in the models.

### References

::: {#refs}
Bresnan, J., Cueni, A., Nikitina, T., Baayen, H., 2007. Predicting the Dative Alternation, in: Bouma, G., Kraemer, I., Zwarts, J.
(Eds.), Cognitive Foundations of Interpretation. Royal Netherlands Academy of Science, Amsterdam, pp. 69–94.

Davies, M., 2008-. The Corpus of Contemporary American English (COCA). Available online at https://www.englishcorpora.org/coca/.
Lenci, A., 2018. Distributional models of word meaning. Annual review of Linguistics, 4, 151-171.

Lenci, A., 2018. Distributional Models of Word Meaning. Annual Review of Linguistics 4 (1): 151–71.

Röthlisberger, M., Grafmiller, J., Szmrecsanyi, B., 2017. Cognitive indigenization effects in the English dative alternation.
Cogn. Linguist. 28, 673–710.

Szmrecsanyi, B., Grafmiller, J., Bresnan, J., Rosenbach, A., Tagliamonte, S., Todd, S., 2017. Spoken syntax in a comparative
perspective: The dative and genitive alternation in varieties of English. Glossa J. Gen. Linguist. 2, 86.
:::

